#!/bin/sh
while read file
do
        case "$1" in
        "r")
                convert -rotate 90 "$file" "$file" ;;
        "c")
                echo -n "$file" | xclip -selection clipboard ;;
        "w")
                feh --bg-scale "$file" && dunstify "🖼  Wallpaper is set" ;;
        esac
done


## press control + x first then your key
