#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/autostart.sh
#bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           5
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focus_follows_pointer true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9

#BSPWM coloring
#bspc config normal_border_color		"#555169"
bspc config normal_border_color		"#1E1E2E"
bspc config active_border_color		"#81a1c1"
bspc config focused_border_color	"#81a1c1"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#eb6f92"
