#!/bin/sh

#LAUNCHERS
$HOME/.config/polybar/launch.sh &
$HOME/.config/bspwm/autostart.sh
#bsp-layout set tall 1 -- --master-size 0.5
#bsp-layout set tall 2 -- --master-size 0.5
#bsp-layout set tall 3 -- --master-size 0.5
#bsp-layout set tall 4 -- --master-size 0.5
#bsp-layout set tall 5 -- --master-size 0.5
#bsp-layout set tall 6 -- --master-size 0.5
#bsp-layout set tall 7 -- --master-size 0.5
#bsp-layout set tall 8 -- --master-size 0.5
#bsp-layout set tall 9 -- --master-size 0.5

#BSPWM configuration
bspc config border_width         3
bspc config window_gap           15
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
#bspc config initial_polarity     second_child

bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true

#bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#555169"
bspc config active_border_color		"#81a1c1"
bspc config focused_border_color	"#81a1c1"
bspc config presel_feedback_color	"#5e81ac"
bspc config urgent_border_color 	"#eb6f92"

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7 8 9

#Fullscreen applications
#bspc rule -a mpv state=fullscreen
#bspc rule -a Vlc state=fullscreen
#bspc rule -a 'Gimp-2.10' state=fullscreen

#Floating applications
bspc rule -a Gcolor3 state=floating
bspc rule -a Galculator state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pavucontrol state=floating sticky=off
bspc rule -a *:*:Picture-in-Picture state=floating sticky=on
#bspc rule -a Xfce4-terminal state=floating
#bspc rule -a Nitrogen state=floating
#bspc rule -a Bitwarden state=floating

#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled
bspc rule -a Xfce4-screensaver-preferences state=tiled
bspc rule -a Gnomecast state=floating

#open applications on specific workspaces
#bspc rule -a *:brave-browser desktop='^1' follow=on
#bspc rule -a 'firefox' desktop='^1' follow=on
bspc rule -a 'pacman-updates' desktop='^9' follow=on
#bspc rule -a 'Thunar' desktop='^2' follow=on
#bspc rule -a 'Catfish' desktop='^2' follow=on
bspc rule -a 'mpv' desktop='^3'  follow=on
#bspc rule -a 'Popcorn-Time' desktop='^3'  follow=on
#bspc rule -a 'WebApp-Netflix1434' desktop='^3' follow=on
#bspc rule -a 'WebApp-AnimeSeries3352' desktop='^3' follow=on
#bspc rule -a 'WebApp-TVTime8052' desktop='^3' follow=on
#bspc rule -a 'WebApp-AnimeSeries0924' desktop='^3' follow=on
#bspc rule -a 'Transmission-gtk' desktop='^7' follow=on
#bspc rule -a 'Gimp-2.10' desktop='^9' follow=on
